---

- hosts: mesos-mon.dmz
  become: true
  vars_files:
    - 'group_vars/web.yml'

  roles:
    - nagios-server

    
# - hosts: example-nagios-clients
#   become: true

#   roles:
#     - nagios-client
